# Generated by Django 3.1.5 on 2021-01-20 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_image2',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='post',
            name='title_image3',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
